version: '3.4'

services:
  weatherapi:
    image: weatherapi
    build:
      context: .  # The context is the current directory
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb_weatherForecast
    ports:
      - "27017:27017"
